version: "3"
volumes:
  sqlite:
services:
  django:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/app
      - sqlite:/var/app/sqlite
    environment:
      ENVIRONMENT: development
      DB_USER: translate
      DB_PASSWORD: password
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      DEBUG: 1
  frontend:
    build:
      context: ./frontend
    ports:
      - 3080:3000
    volumes:
      - ./frontend/pages:/var/app/pages
      - ./frontend/public:/var/app/public
      - ./frontend/src:/var/app/src
      - ./frontend/styles:/var/app/styles
