version: "3"
services:
    django:
        build:
            context: ./backend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/var/app
    frontend:
        build:
            context: ./frontend
        ports:
            - 3080:3000
        volumes:
            - ./frontend:/var/app
