version: "3"
services:
    django:
        build:
            context: ./backend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/var/app
    frontend:
        build:
            context: ./frontend
        ports:
            - 3080:3000
        volumes:
            - ./frontend/pages:/var/app/pages
            - ./frontend/public:/var/app/public
            - ./frontend/src:/var/app/src
            - ./frontend/styles:/var/app/styles
