version: "3"
volumes:
  dbdata:
  certs:
  static:
services:
  db:
    image: postgres:13
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
    volumes:
        - dbdata:/var/lib/postgresql
  django:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/app
      - static:/var/static
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/pages:/var/app/pages
      - ./frontend/public:/var/app/public
      - ./frontend/src:/var/app/src
      - ./frontend/styles:/var/app/styles
    environment:
      NODE_ENV: production
  nginx:
    build:
      context: ./nginx
    volumes:
      - certs:/etc/certificates
      - static:/var/static
    ports:
      - 80:80
      - 443:443
    environment:
      APP_DOMAIN: translate.zetkin.org
      APP_USE_TLS: ''