# Generated by Django 3.2 on 2021-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('repository_url', models.URLField()),
                ('locale_files_path', models.CharField(max_length=128)),
            ],
        ),
    ]
