# Generated by Django 3.2 on 2021-05-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=64)),
                ('from_repo', models.BooleanField()),
                ('file_path', models.CharField(max_length=128)),
                ('object_path', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.project')),
            ],
        ),
    ]
