# Generated by Django 3.2 on 2021-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_auto_20210504_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('repository_url', 'locale_files_path')},
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('file_path', 'object_path')},
        ),
    ]
