# Generated by Django 3.2 on 2021-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20210504_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='translations.Language'),
        ),
    ]
