# Generated by Django 3.2 on 2021-05-05 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_auto_20210505_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('file_path', 'object_path', 'created_at')},
        ),
    ]
