# Generated by Django 3.2 on 2021-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0009_alter_translation_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('file_path', 'object_path', 'created_at', 'language', 'project')},
        ),
    ]
