# Generated by Django 3.2 on 2021-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0012_project_last_sync_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
