# Generated by Django 3.2 on 2021-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0013_alter_project_last_sync_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yaml_indentation',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='locale_files_path',
            field=models.CharField(help_text="Path to the locale files within the project. Do not include leading or trailing slashes. Example: 'src/locale'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_name',
            field=models.CharField(help_text="The repo name including the project if there is one. Example: 'zetkin/organize.zetk.in'", max_length=256),
        ),
    ]
