# Generated by Django 3.2 on 2021-06-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0015_alter_project_languages'),
        ('translations', '0015_auto_20210616_1104'),
    ]

    operations = [
    ]
